### ISSUE TITLE
Issue in Chinese interval localization

### ISSUE THREAD

**Issue by louislkam** [mattt/FormatterKit#199]
Chinese in time interval puts a space between the time unit and "ago" eg. 3 小时 前, where there shouldn't be a space.

**Comment by denniszxxc** [comment]
My temporary workaround solution is to subclass `TTTTimeIntervalFormatter `. 

Override `deicticExpressionFormat` property getter and  `return @"%@%@";` When system language is chinese.

**Comment by yiplee** [comment]
add **"Deictic Expression Format String" = "%@%@";** into zh-Hans/FormatterKit.strings

**Comment by yas375** [comment]
Does it apply to both Traditional and Simplified?

**Comment by yas375** [comment]
@louislkam @denniszxxc @yiplee actually I've just explored that this was fixed 9 month before this issue was opened... Here is the fix: https://github.com/mattt/FormatterKit/commit/8c755108ab2806f5aef797232900ea3def8caa70

Now, we also have localization specific tests and they also prove there is no space in between: https://github.com/mattt/FormatterKit/blob/master/Example/Tests-Chinese-Simplified/TimeIntervalFormatterTests.swift#L25

Please upgrade to the latest version.
